name: sdv1
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.9.5  # Updated by JStyborski from 1.4.2 to accommodate easier VAE finetuning
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.7.0  # Updated by JStyborski from 0.6.0 to comply with pl 1.9.5
    - kornia==0.6
    - piq==0.8.0  # Added by JStyborski to support LPIPS loss - doesn't seem to cause issues
    - accelerate==0.34.2  # Added by JStyborski to support text-inversion script
    - scikit-learn==1.3.2  # Added by JStyborski
    - matplotlib==3.6.3  # Added by JStyborski
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - advertorch@git+https://github.com/BorealisAI/advertorch.git  # Added by JStyborski to mimic MIST
    - -e .
    